### PR TITLE
Added descriptive text to readmemd

### PR DESCRIPTION
**Pull request by fabiosenracorrea**
In this branch i added a short description into readme.md to my repository.

### CODE REVIEW

**Comment by danieljs-dev** [comment]
Muito bom. Parabéns!

**Comment by paulo-frazao** [comment]
atividade concluída, boraaaa \o/

**Comment by EliasCarvalho20** [comment]
Bora pra dominar esse Git haha.

**Comment by deborapolesel** [comment]
Muito bom Fábio :+1: :rocket: Parabéns

**Comment by rodrigodesantanaribeiro** [comment]
Top! #goTrybe

**Pull request merged**
